### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Daniel4-Scratch** [SnapForks/SnapForks#13]
## Offline SnapForks
@stickgamer requested an offline version of SnapForks I need some help with that too. 
Repo: [SnapForks/SnapSporks](https://github.com/SnapForks/SnapSporks/)

# 
Posted by @Daniel4-Scratch

**Comment by Daniel4-Scratch** [comment]
Please leave a reply if you can help.

**Comment by icositetrachoron-programmer** [comment]
To check if a project exists, you would need to make a HTTP request to the server, so you would do this:
```js
let username, project, url;
async function submit() {
  project = encodeURIComponent(document.getElementById('txt1').value);
  username = encodeURIComponent(document.getElementById('txt2').value);
  const req = await fetch(`https://cors-anywhere.herokuapp.com/https://snap.berkeley.edu/projects/${username}/${project}`);
  if(req.ok) {
    //console.log('exists');
    loadProject();
  } else if(req.status === 404){
    alert('That project does not exist');
  }
}
function loadProject() {  
 
 
 url=`https://snap.berkeley.edu/embedproject=${project}&user=${username}&showTitle=true&showAuthor=true&editButton=true&pauseButton=true`;
document.getElementById('if').src = url;
document.getElementById('code').value = url;
}
```

**Comment by icositetrachoron-programmer** [comment]
As for the offline version, you would have to port the whole Snap! application offline unless you just want to embed the project with an iframe.

**Comment by Daniel4-Scratch** [comment]
> To check if a project exists, you would need to...
Can you make a PR and example project of it working please.

**Comment by icositetrachoron-programmer** [comment]
@Daniel4-Scratch if that wasn't clear I'll explain in more detail.
When you use SnapForks, it displays the project in an iframe, so your page requests the project page => the server responds with the project => the page receives the HTML document and displays it in the document. If you want offline capability you have to think about whether you want it to be truly offline or for it to depend on the Snap! server. If you want absolute offline capability then you would have to also make Snap! offline for it to read the XML files. If you just want it as a desktop app but you are okay with depending on the server you could just modify the request URL (I think).
