### ISSUE TITLE
Could not find shared and published project

### ISSUE THREAD

**Issue by sfederici** [SnapForks/SnapForks#3]
I tested SnapFork with a Scratch project converted by means of Snapinator https://snap.berkeley.edu/project?user=s_federici&project=real%20time%203D%20rendering. I shared and published the project, but SnapFork says the project does not exist.

**Comment by Daniel4-Scratch** [comment]
Ok, thanks , i'll look into this

**Comment by Daniel4-Scratch** [comment]
hmm.. it works fine

**Comment by sfederici** [comment]
I wrote "real time 3D rendering" in the "project name" box and s_federici in the "author" box. SnapFork can't find the project.

**Comment by Daniel4-Scratch** [comment]
Spelling errors? Or bug? Try another project, see if that works

**Comment by sfederici** [comment]
Maybe a spelling error. Now I was able to test it. At least for this project https://snap.berkeley.edu/snap/snap.html#present:Username=s_federici&ProjectName=realtime3Drendering, Snap and SnapFork apparently seem to run it at the same speed. Is SnapFork supposed to speed up the execution of Snap Projects as Forksphorus and Turbowarp do for Scratch?

**Comment by Daniel4-Scratch** [comment]
Not so fast, but I cloud add a FPS option

**Comment by sfederici** [comment]
It would be great!

**Comment by Daniel4-Scratch** [comment]
Thanks, for the report, I will try to add a FPS option on SnapForks and this bug may just be your OS or Snap<em>!</em>

**Comment by Daniel4-Scratch** [comment]
Issue locked due to being resolved

**Comment by Daniel4-Scratch** [comment]
#5
