### ISSUE TITLE
"#..." is Ignored

### ISSUE THREAD

**Issue by R4356th** [SnapForks/SnapForks#9]
**Describe the bug**

**To Reproduce**
1. Use #something as a project name or author

**Expected behavior**
They should not be ignored.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest version
 - Version 1.0.0

**Additional context**
This is a HTML issue, I believe.
Edit by @Daniel4-Scratch: HTTPS/URL issue

**Comment by Daniel4-Scratch** [comment]
Hmm. Thanks, I'll look into this. 🤔

**Comment by Daniel4-Scratch** [comment]
The # is a like ignored and for page heading links (eg: https://github.com/SnapForks/SnapCups#contributors-4), and the # may interfere with Snap<em>!</em>.

**Comment by R4356th** [comment]
> The # is a like ignored and for page heading links (eg: https://github.com/SnapForks/SnapCups#contributors-4), and the # may interfere with Snap_!_.

Yes, I know. But there could still be a way of getting around this.

**Comment by Daniel4-Scratch** [comment]
Ok, I'll do some research..

**Comment by R4356th** [comment]
What about replacing # s with %232?

**Comment by Daniel4-Scratch** [comment]
try that

**Comment by Daniel4-Scratch** [comment]
yes, or you can give me the project and author info.

**Comment by Daniel4-Scratch** [comment]
How to we fix the conflict RP?
